apiVersion: v1
kind: Service
metadata:
  name: property-backend
  labels:
    app: property-backend
spec:
  type: ClusterIP
  selector:
    app: property-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
